import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Navigation from './Navigation';
import bgImg from './images/surf-background-cover-page.jpg';

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Maggie Bowen&#39;s Portafolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <div className={styles.bgWrap}>
          <Image
            alt="photo of Maggie surfing"
            src={bgImg}
            placeholder="blur"
            quality={100}
            fill
            style={{
              objectFit: 'cover',
            }}
          />
        </div>
        <main className={styles.main}>
          <h1 className={styles.title}>Maggie Bowen</h1>
          <p className={styles.description}>
            <i>Artist, Coder, Teacher</i>
          </p>

          <Navigation />
        </main>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export default Home;
